version: '3'

vars:
  APP_NAME: "FileMoverExpressUI"
  BIN_DIR: "../../dist"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 4200}}'
  BUILD_VERSION: '{{.BUILD_VERSION | default "0.0.0-local-dev"}}'

includes:
  common: ./build/Taskfile.yml
  windows:
    taskfile: ./build/windows/Taskfile.yml
    vars:
      BUILD_VERSION: '{{.BUILD_VERSION}}'
  darwin:
    taskfile: ./build/darwin/Taskfile.yml
    vars:
      BUILD_VERSION: '{{.BUILD_VERSION}}'
  linux:
    taskfile: ./build/linux/Taskfile.yml
    vars:
      BUILD_VERSION: '{{.BUILD_VERSION}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  test:
    desc: Run Wails Go tests
    cmds:
      - go test -gcflags="all=-N -l" -short -v -cover -coverprofile coverage.out ./...
      - go tool cover -html coverage.out -o coverage.html
